### ISSUE TITLE
Remover índices desnecessários

### ISSUE THREAD

**Issue by julianalucena** [redu/apps#104]
Verificar índices do BD que não são utilizados.

**Comment by embs** [comment]
As modificações foram motivadas por instruções anteriores de @julianalucena, leitura de um [artigo](http://tomafro.net/2009/08/using-indexes-in-rails-index-your-associations) que trata do tema e pesquisa na [API do Rails](http://api.rubyonrails.org/classes/ActiveRecord/Migration.html).

Os índices que eram adicionados com a sintaxe utilizada para associações polimórficas

``` ruby
add_index :app_category_associations, [:app_id, :category_id]
```

foram refatorados para índices simples

``` ruby
add_index :app_category_associations, :app_id
add_index :app_category_associations, :category_id
```

Além disso, foram removidos índices que não são utilizados (especificamente, os que indexavam a coluna `name` de entidades da hierarquia) e foi adicionado um índice para a coluna `environment_id` na tabela de Courses.
