### ISSUE TITLE
Indicativo de lista vazia quando não há Disciplinas criados

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/apps#110]
No primeiro passo do Checkout de aplicativos, quando não há disciplina criada, não é mostrado nenhum indicativo de lista vazia.

Uma ideia é dizer que o usuário não possui disciplinas e aponta-lo para /ensine.

**Comment by filipewl** [comment]
Vou perguntar a @sergiofontes o que ele quer mostrar.

**Comment by guiocavalcanti** [comment]
https://github.com/redu/apps/commit/4db4af779d6d900a56d7bc09690cd39f2970e0b9
