### ISSUE TITLE
Não é possível votar nos valores 1 ou 5

### ISSUE THREAD

**Issue by filipewl** [redu/apps#113]
Não estou conseguindo votar nos valores 1 ou 5 na classificação de um aplicativo. Debuguei e os valores estão indo corretos para `apps#rate` mas em `apps#show`, `@user_rating = @app.reputation_for(:rating, nil, @user)` sempre retorna 2 caso tenha votado em 1 ou 4 caso tenha votado em 5.

**Comment by fltiago** [comment]
@embs e @filipewl resolverei esse issue. I've just assign to me. Abraço a todos.
