### ISSUE TITLE
Verificar possibilidade de remoções no Core causarem inconsistência

### ISSUE THREAD

**Issue by julianalucena** [redu/apps#116]
Por exemplo, caso um Course seja removido no Core, o mesmo será removido do Portal, mas seus Spaces não (do modo que está atualmente). Caso o space seja manipulado, isto pode causar erros.

A melhor alternativa é adicionar dependent destroy e o Apps manter a consistência ou ele não ser responsável por isso e esperar a resposta do Core?

**Comment by julianalucena** [comment]
@igorcalabria, se chegar uma remoção de um curso que já foi removido, como o Zombify se comporta?

**Comment by igorcalabria** [comment]
@julianalucena, se chegar uma remoção para um entidade que não existe, ele ignora.
