### ISSUE TITLE
Variáveis em português em UntiedObserverSpec

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/apps#117]
https://github.com/redu/apps/blob/master/spec/lib/untied_observer_helper_spec.rb#L10

**Comment by guiocavalcanti** [comment]
Same here: https://github.com/redu/apps/blob/master/spec/lib/payload_proccessor_spec.rb#L9

**Comment by julianalucena** [comment]
https://github.com/redu/apps/blob/master/spec/lib/untied_observer_helper_spec.rb#L232
https://github.com/redu/apps/blob/master/spec/lib/untied_observer_helper_spec.rb#L105
