### ISSUE TITLE
Usuário redu admin deve ter autorização total

### ISSUE THREAD

**Issue by julianalucena** [redu/apps#122]

**Comment by embs** [comment]
@julianalucena, é tranquilo resolver isso? Se sim, me dá umas dicas aí que eu tento resolver.

**Comment by julianalucena** [comment]
Sim, @embs. No caso, o usuário deverá ter a coluna `role`, assim como ocorre no Core, para identificá-lo como redu_admin. Após isso, colocar a lógica no Ability.

**Comment by julianalucena** [comment]
@embs, @guiocavalcanti, não deveríamos ter feito uma regra geral que faz com que o administrador tenha autorização para tuo?

**Comment by embs** [comment]
Como seria isso, @julianalucena? Eu lembro que busquei inspiração no código do Redu para escrever essas regras de permissão. No Redu não é feito assim como você sugeriu, é?

**Comment by guiocavalcanti** [comment]
Entendi e concordo com o que @julianalucena falou. Seria uma regra genérica do tipo `can :manage, :all, is_admin?: true` ou `can :manage, :all, core_role: 1`

**Comment by embs** [comment]
@guiocavalcanti, não entendi onde essa regra seria aplicada (isto é, onde seria chamado o `authorize! :manage, :all`. Ficaria junto com os outros `authorize!` ou dentro do código dos abilities?

**Comment by guiocavalcanti** [comment]
@embs a chamada seria a mesma: `authorize! :manage, algum_objeto` e ele passaria quando o `core_role == 1`.
