### ISSUE TITLE
Adicionar olark ao Portal

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/apps#132]
O código, provavelmente, é o mesmo do core.

**Comment by guiocavalcanti** [comment]
https://github.com/redu/redu/blob/master/app/views/shared/_olark.html.erb

**Comment by guiocavalcanti** [comment]
https://github.com/redu/redu/blob/master/public/javascripts/olark.js

**Comment by julianalucena** [comment]
Só aparece em desenvolvimento.
