### ISSUE TITLE
Layout quebrado em App#index

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/apps#140]
http://aplicativos.redu.com.br/aplicativos?filter%5B%5D=1

![](https://dl.dropbox.com/u/77225/redu/Screen%20Shot%202012-11-26%20at%204.22.33%20PM.png)

**Comment by filipewl** [comment]
Não pude reproduzir o mesmo erro no Windows:

![erro](http://s3.amazonaws.com/awesome_screenshot/1104950?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1353968424&Signature=b2G1dLrd62mN73Cu54p9QPgl4ow%3D)

Vou verificar no Linux depois. Se for Mac-only só vou poder inspecionar amanhã.
