### ISSUE TITLE
Verificar os REAs que tem creative commons e os que não tem.

### ISSUE THREAD

**Issue by andredm** [redu/apps#149]
Igor disse que alguns REA são creative commons e outros não, mas no Redu todos estão com a logo do CC-BY.  Essas informações já vieram quando foi feito o crawler.

Segue dois exemplos:

É CC -> http://aplicativos.redu.com.br/aplicativos/2

Não é CC -> http://aplicativos.redu.com.br/aplicativos/12

**Comment by guiocavalcanti** [comment]
@igorcalabria, talvez isso te ajude: https://github.com/redu/apps/wiki/Importando-Aplicativos

Posta o gist do script aqui que eu rodo em produção.

**Comment by guiocavalcanti** [comment]
26dfc8278459455f1d864ef20df7e2788d9e408d
