### ISSUE TITLE
Testes falhando em user_session_controller_spec e application_controller_spec

### ISSUE THREAD

**Issue by igorcalabria** [redu/apps#151]
Failures:

  1) UserSessionsController POST 'destroy' the request is through AJAX should do a redirect back with window.location
     Failure/Error: response.body.should \
       expected "window.location.pathname='/';" to include "window.location='http://whereiwas.com'"
     # ./spec/controllers/user_sessions_controller_spec.rb:95:in `block (4 levels) in <top (required)>'

  2) ApplicationController AuthlogicHelpers when user is logged in current_user returns the logged user
     Failure/Error: controller.send(:current_user).should == @user
       expected: #<User id: 172, core_id: 43, token: nil, login: "user43", first_name: "Joao", last_name: "da Silva", role_cd: 1, thumbnail_file_name: "user_thumb.png", thumbnail_content_type: "image/png", thumbnail_file_size: 2488, thumbnail_updated_at: "2012-11-28 11:49:09", created_at: "2012-11-28 11:49:10", updated_at: "2012-11-28 11:49:10", crypted_password: "91bb3da8a5de338cdfa89cf1e5db9402c36f1d52", password_salt: "UNJMwThFHUD2LE8LJojv", email: "user43@email.com", persistence_token: "679fd258b7d2e3f98c5795a12bec5c9297d11aa6fe4e54ff512...", zombie: false>
            got: nil (using ==)
     # ./spec/controllers/application_controller_spec.rb:66:in `block (4 levels) in <top (required)>'

  3) ApplicationController AuthlogicHelpers when user is logged in current_user_session returns the session
     Failure/Error: controller.send(:current_user_session).should be
       expected nil to evaluate to true
     # ./spec/controllers/application_controller_spec.rb:60:in `block (4 levels) in <top (required)>'

**Comment by embs** [comment]
@julianalucena, essa bronca aí é tua, né?

**Comment by guiocavalcanti** [comment]
@julianalucena, please, please, solve it.

**Comment by julianalucena** [comment]
Everybody happy now. @guiocavalcanti @embs

**Comment by embs** [comment]
/o/

**Comment by guiocavalcanti** [comment]
:+1:
