### ISSUE TITLE
Criar uma classe para abstrair o formato do model_helper.yaml

### ISSUE THREAD

**Issue by igorcalabria** [redu/apps#155]
O helper do untied está muito dependente da forma com que os dados são organizados no yaml, seria interessante criar uma classe que abstraísse o acesso a esses dados. Dessa forma, só ia ser necessário mexer em uma classe no caso de uma mudança no formato do yaml(ex: Refatoração de um nome)

**Comment by embs** [comment]
Issue movido [pra cá](https://github.com/redu/untied-consumer-sync/issues/1).
