### ISSUE TITLE
A página de aplicativos favoritos está inacessível

### ISSUE THREAD

**Issue by andredm** [redu/apps#169]
Pessoal,

Tentei acessar os meus aplicativos favoritos para não consegui, apareceu: "We're sorry, but something went wrong."

Segue o link: http://aplicativos.redu.com.br/usuarios/andremoraes/favoritos

**Comment by filipewl** [comment]
@andredm tenta denovo aí. Entrei aqui no meu e pegou normal. Pode ter sido algo temporário com o servidor.

**Comment by andredm** [comment]
@filipewl  acabei de tentar e continua com o mesmo problema  :/

**Comment by embs** [comment]
@andredm, deve ser algo específico de teus aplicativos favoritos por que aqui também consigo acessar. Precisamos ver o log para diagnosticar o problema. Além disso, a página de erro 500 (no servidor) deveria ser renderizada em vez da página de erro do Rails.

**Comment by guiocavalcanti** [comment]
@embs, o erro é esse. Aparentemente é algo no helper, você pode dar uma olhada?

```
Started GET "/usuarios/andremoraes/favoritos" for 187.78.221.41 at 2013-01-11 18:21:44 +0000
Processing by FavoritesController#index as HTML
  Parameters: {"locale"=>"pt-BR", "user_id"=>"andremoraes"}
  Rendered favorites/index.html.erb within layouts/application (2.2ms)
Completed 500 Internal Server Error in 25ms

ActionView::Template::Error (wrong number of arguments (2 for 3)):
    19:       <div class="filters">
    20:         <% @favorite_apps_filters.uniq.each do |cat| %>
    21:           <%= link_to "#{cat.name} #{parentize(@favorite_apps_filters_counter[cat.name])}",
    22:                       user_favorites_path(current_user, filter: filters_url(@filter, cat)),
    23:                       class: filter_class(@filter, cat) %>
    24:         <% end %>
    25:       </div>
  app/helpers/apps_helper.rb:5:in `filters_url'
  app/views/favorites/index.html.erb:22:in `block in _app_views_favorites_index_html_erb__65304357_101910570'
  app/views/favorites/index.html.erb:20:in `each'
  app/views/favorites/index.html.erb:20:in `_app_views_favorites_index_html_erb__65304357_101910570'

```

**Comment by embs** [comment]
[Resolvido](https://github.com/redu/apps/commit/2061e2d09c12a287b8a0b2c2401e88bb08fe4e66).
