### ISSUE TITLE
Fonte do título do chat do Olark embaçada

### ISSUE THREAD

**Issue by embs** [redu/apps#172]
O texto do título da caixa de diálogo do Olark está com um estilo (sombreado ou negrito – não consegui discernir) diferente do Redu que prejudica a legibilidade.

![Screen shot 2013-01-10 at 5 32 08 PM](https://f.cloud.github.com/assets/1200033/58114/874f24ce-5b65-11e2-9703-8a86131ef188.png)

**Comment by filipewl** [comment]
Xá que eu resolvo.

**Comment by embs** [comment]
@filipewl já resolveu, foi? Aqui tá aparecendo direitinho agora. Se sim, fecha aí o issue?

**Comment by julianalucena** [comment]
Imagem tirada hoje:

![Screen Shot 2013-02-06 at 9 24 10 AM](https://f.cloud.github.com/assets/387579/131413/2123d44e-7058-11e2-9bf5-458d8893e9cb.png)
