### ISSUE TITLE
Imagem de aplicativo com altura maior que 90px

### ISSUE THREAD

**Issue by filipewl** [redu/apps#185]
A imagem do aplicativo está com altura maior que `90px`. Resolver primeiro em: https://github.com/redu/ui-components/issues/33.

http://aplicativos.redu.com.br/aplicativos?utf8=%E2%9C%93&search=body

![bug](https://f.cloud.github.com/assets/381395/71129/9dc15122-5fd5-11e2-9850-e5658c7d56c6.png)

**Comment by guiocavalcanti** [comment]
@filipewl resolvido em 66bdda769af822508e8dcc026ed53d674d1da7be
