### ISSUE TITLE
Aumentar altura do iframe de preview de aplicativo

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/apps#186]
Setar a altura para 420px

**Comment by guiocavalcanti** [comment]
@filipewl, pode resolver isso ou alocar para alguém?

**Comment by filipewl** [comment]
@guiocavalcanti vê aí https://github.com/redu/apps/pull/187.

**Comment by guiocavalcanti** [comment]
@filipewl apareceu uma barra de rolagem.

![Screen Shot 2013-01-16 at 10 57 34](https://f.cloud.github.com/assets/188599/71339/c4c60eca-5fe4-11e2-9b32-10125d3a4c5a.png)

Reabri o issue

**Comment by guiocavalcanti** [comment]
@filipewl up. Tem um parceiro da gente aguardando isso.

**Comment by filipewl** [comment]
@guiocavalcanti beleza, vou resolver ainda hoje.
