### ISSUE TITLE
Botão "Adicionar a Disciplina" sem indicativo de requisição AJAX

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/apps#197]
Ao clicar em:

![Screen Shot 2013-02-06 at 09 11 27](https://f.cloud.github.com/assets/188599/131376/c921bfd2-7056-11e2-8a12-19e5efa86cc7.png)

O spinner não é mostrado. Dependendo da latência o usuário tende a clicar diversas vezes por falta de feedback da interface.

@filipewl faz a triagem ai ;)

**Comment by guiocavalcanti** [comment]
@thaisbione esse isse foi aberto há 1 mês. Alguma atualização?

**Comment by filipewl** [comment]
Está nesta sprint pra gente fazer, mas a prioridade no momento são as aulas de ESE.
