### ISSUE TITLE
Responder comentário cria também um novo comentário

### ISSUE THREAD

**Issue by filipewl** [redu/apps#206]
http://aplicativos.redu.com.br/aplicativos/13

![apps-issue](https://f.cloud.github.com/assets/381395/198464/4770f9ba-805c-11e2-8fe7-b5b51ec6721a.png)

**Comment by julianalucena** [comment]
Comentários de especialista também aparecem duplicados:

![Screen Shot 2013-02-27 at 8 46 33 PM](https://f.cloud.github.com/assets/387579/203458/07068b9c-8138-11e2-9453-77a6847d0f4e.png)

**Comment by embs** [comment]
Na verdade eles não estão sendo criados em duplicidade no banco. O problema está apenas na exibição duplicada (como @julianalucena especificou no comentário acima).

Não consegui reproduzir localmente o erro da duplicidade de comentários exibidos quando se cria uma resposta. Consegui reproduzir a duplicidade quando se cria comentário especializado e identifiquei o [trecho de código problemático](https://github.com/redu/apps/commit/126247abfb75ab274dd9df4494212c0a6c6e15a4#L0L162). De qualquer maneira, alterei também a maneira [como são filtrados](https://github.com/redu/apps/commit/126247abfb75ab274dd9df4494212c0a6c6e15a4#L0R134) os comentários de especialista.

@julianalucena, é tranquilo usar o `select` assim na view ou melhor criar um helper? Lembro que a utilização do select tem como vantagem não só a garantia de exibir os tipos certos de comentários mas também a possível economia de idas ao banco de dados -- que são realizadas pelos scopes.

**Comment by julianalucena** [comment]
Olá, @embs,

Eu identifiquei ambos os erros e já estou trabalhando em um refactor (em relação ao erro com as Answers) desde ontem ao fim da tarde, por causa de um problema na implementação da STI.

Também fiz a correção deste erro dos comments, no caso, atribuí às variáveis separadamente lá no controller.

Hoje vou dar push e tu pode dar uma olhada.

**Comment by embs** [comment]
@julianalucena, só vi a atribuição do issue a você depois de ter mandado o pull request. Perdão pela falta de atenção. :B

Então tá beleza, darei uma olhada na tua correção. Eu não havia atentado para a utilização do `type` (que, pelo que parece) faz Rails utilizar automaticamente STI -- ainda que a intenção ao adicionar diferentes tipos de comentários a priori não tenha sido implementar esse padrão.

**Comment by julianalucena** [comment]
Beleza, @embs.
