### ISSUE TITLE
Erro antes de abrir a modal de adicionar aplicativo a disciplina

### ISSUE THREAD

**Issue by filipewl** [redu/apps#207]
Acho que é só em desenvolvimento, pois está normal em produção agora. Não sei se eu tinha que ter feito algo antes. Já populei o banco com os aplicativos e criei o usuário com `populate:hierarchy`. Estou tentando ver esta modal pois estou atualizando o bootstrap e muita coisa pode ter quebrado.

![apps-issue](https://f.cloud.github.com/assets/381395/198477/b4b4d802-805c-11e2-8be9-9dc31eda80b1.png)

**Comment by julianalucena** [comment]
Não consegui reproduzir. Caso torne a ocorrer, reabre.
