### ISSUE TITLE
Indicativo de lista vazia na listagem de Disciplinas

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/apps#210]
Havia feito essa modificação pois a falta do indicativo de lista vazia estava levando os usuários a acreditar que havia um erro. Não consultei o time de design. Seria interesante utilizar o componente de interface mais indicado aqui:

![Screen Shot 2013-03-01 at 13 26 13](https://f.cloud.github.com/assets/188599/210295/cde8e534-828c-11e2-80c1-15217e08b992.png)

**Comment by filipewl** [comment]
Vou perguntar a Sérgs.

**Comment by sergiofontes** [comment]
Recomendo adicionar o aviso utilizando-se do mesmo estilo da Legenda dessas listas (aquele aviso embaixo do título do Curso com o número de Disciplinas).

![issue 1 - Lista vazia de Curso-01](https://f.cloud.github.com/assets/723163/218173/9d0cd1ce-8501-11e2-9c51-2047f8eac65d.png)

Exportei um arquivo (**Issue#1 - Lista vazia de Disciplinas.ai**) contendo somente este exemplo de lista.
Vocês podem encontrá-lo em: **redu-design/3. UI/Protótipos & Versões/1.3.6/#rsc**

**Comment by guiocavalcanti** [comment]
:+1: :hand:

**Comment by filipewl** [comment]
Coloquei pra resolver nesta sprint.

**Comment by guiocavalcanti** [comment]
Thanks @filipewl

**Comment by filipewl** [comment]
@brunomachado, lembra de fazer essa aqui.
