### ISSUE TITLE
Atualizar os botões a barra de navegação global

### ISSUE THREAD

**Issue by filipewl** [redu/apps#220]
Atualizar o botão atual de `Cursos` para `Ambientes` e seu link.

Atual do portal:
![apps](https://f.cloud.github.com/assets/381395/358590/713b2b0c-a146-11e2-9a67-ef0575c392ba.png)

Atual no Redu:
![redu](https://f.cloud.github.com/assets/381395/358591/76fc3220-a146-11e2-9c69-0bcd5e2a5366.png)

**Comment by julianalucena** [comment]
@filipewl, este issue deve ser high, porque o menu cursos dá 404.

**Comment by filipewl** [comment]
@julianalucena eita, vou resolver agora.
