### ISSUE TITLE
Usar apenas uma forma de chaves para Hashes

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/apps#25]
Acho melhor utilizar `:nome => 'valor'`

**Comment by embs** [comment]
@guiocavalcanti, como foi instituida uma nova sintaxe para chaves de hashes (Ruby 1.9), optamos por utilizá-la. No entanto, ainda existem arquivos do código em que a sintaxe antiga é usada. Conversei com @igorcalabria para renovarmos isso paulatinamente, à medida em que formos modificando arquivos de código-fonte.

Vale salientar a intenção de não misturar sintaxes antiga e nova em um mesmo arquivo de código. Tudo bem?

**Comment by guiocavalcanti** [comment]
@embs, beleza!
