### ISSUE TITLE
Paginação deve manter filtros

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/apps#42]

**Comment by embs** [comment]
A paginação já mantém filtros. No entanto, detetei um comportamento anômalo hoje ao selecionar mais de um filtro. Quando apenas um é selecionado, a paginação funciona adequadamente. A bronca é que quando são selecionados – ao que me parece – pelo menos dois filtros, todos os Apps são retornados. Talvez seja algo relacionado ao sunspot. Irei verificar.

**Comment by embs** [comment]
Notei que os filtros da paginação com endless não eram repassados ao link 'Mostrar Mais' (renderizado via js). @filipewl já corrigiu isso.
