### ISSUE TITLE
Contar Comentários, Visualizações e Resenhas de App

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/apps#5]

**Comment by embs** [comment]
Resolvido. O total de comentários e resenhas já era disponível (através da contagem de associações). O total de visualizações foi criado [neste commit](https://github.com/redu/apps/commit/3941205cb405594edbfd517769c7aa63a6fe156f) e adicionado à view show de App [neste outro commit](https://github.com/redu/apps/commit/620c4c229b6ea225ac035d11bdc8054f48381423).
