### ISSUE TITLE
Utilizar paginação estática

### ISSUE THREAD

**Issue by filipewl** [redu/apps#62]
Utilizar a paginação do tipo estática (ex: Anterior, 1, 2, ..., X, Próximo) na paginação dos aplicativos e comentários ao invés da atual que é feita com AJAX.

**Comment by embs** [comment]
[Fechado](https://github.com/redu/apps/commit/888dbc2b2b2f69b27121f96172d2bc7bacb1639a)!

**Comment by embs** [comment]
Os guidelines de @sergiofontes foram os seguintes:
1. Mostrar páginas próximas à visualizada pelo usuário;
2. Mostrar ao menos 6 páginas próximas à visualizada pelo usuário;
3. Mostrar a primeira e última páginas;

Se necessário, utilizar reticências para gaps entre páginas;
