### ISSUE TITLE
Utilizar gems para verificação de otimização das consultas ao banco de dados

### ISSUE THREAD

**Issue by embs** [redu/apps#67]
Indicadas por @fltiago e @julianalucena:
- https://github.com/flyerhzm/bullet
- https://github.com/josevalim/rails-footnotes

**Comment by embs** [comment]
É aconselhável implementar esta melhoria apenas quando o código estiver suficientemente estável – sem a adição de muitas modificações / quando as outras melhorias ou correções de código tiverem sido implementadas – por que modificações no código costumam introduzir novos problemas de performance relacionados à consulta ao BD.

**Comment by julianalucena** [comment]
Okay.
