### ISSUE TITLE
Efeito esquisito no hover do logotipo do Redu

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/apps#73]
Está sendo mostrado um traço azul no canto superior esquerdo do elemento.

Testei no chrome versão 23.0.1271.64

**Comment by filipewl** [comment]
@brunomachado tava tentando o mesmo problema na Central de Ajuda. Vou ver como ele resolveu.

**Comment by brunomachado** [comment]
@filipewl .nav-global-brand { text-decoration: none; }

**Comment by filipewl** [comment]
@brunomachado, é, tinha visto teu commit consertando. Agora a correção deveria estar no repo do bootstrap, pois faz parte do elemento de navegação global. :<

**Comment by brunomachado** [comment]
@filipewl Eita, foi mal. Nem tinha me tocado disso.
