### ISSUE TITLE
Links para o Redu hardcoded

### ISSUE THREAD

**Issue by filipewl** [redu/apps#74]
Várias vezes tive que escrever na mão links que apontavam para o Redu, como por exemplo perfil do usuário nos comentários do app e links do dropdown da barra de navegação global. Pra não ficar hardcoded acho que deveria ser criado alguma variável global (algo do tipo). Basta procurar no projeto por "http://www.redu.com.br/".

**Comment by guiocavalcanti** [comment]
http://stackoverflow.com/questions/3622706/creating-a-rails-route-to-an-external-url

**Comment by filipewl** [comment]
@guiocavalcanti, não sei se essa solução vai servir pra esse caso. Não é questão de dar match numa rota do portal pro Redu não.

Pelo menos não entendi como isso funcionária nesses casos por exemplo: https://github.com/redu/apps/blob/master/app/views/shared/_nav_global.html.erb#L27
