### ISSUE TITLE
Aprimorar lógica de incremento de visualização de aplicativo

### ISSUE THREAD

**Issue by embs** [redu/apps#75]
O contador de visualizações de aplicativo é incrementado sempre que a action AppsController#show é chamada. Em decorrência disso, incrementa-se em ocasiões inadequadas (algumas requisições assíncronas, por exemplo).

**Comment by guiocavalcanti** [comment]
@embs atriui a @igorcalabria

**Comment by embs** [comment]
O problema decorrente do recarregamento constante da página de visualização do aplicativo -- que acarretava a deturpação da quantidade de visualizações -- foi mitigado pelo fechamento das issues #175 e #181.
