### ISSUE TITLE
Contador de comentários no app index não leva em conta respostas

### ISSUE THREAD

**Issue by filipewl** [redu/apps#78]
Percebi agora que, diferentemente do contador de comentários da página individual de um aplicativo (`views/apps/show`, [linha](https://github.com/redu/apps/blob/master/app/views/apps/show.html.erb#L33)) que leva em conta os comentários + respostas, o contador de comentários do índice (`views/shared/app`, [linha](https://github.com/redu/apps/blob/master/app/views/shared/_app.html.erb#L37)) conta somente os comentários, sem respostas. 

Isto está causando uma discrepância entre o contador de comenários na página de índice e na página individual do aplicativo.

**Comment by embs** [comment]
@filipewl, dá uma olhada no [helper](https://github.com/redu/apps/commit/d1b9fd49ffc2d90f40e5254ab189650fb9103161#L0R50) que criei pra contar os comentários de um App. Podes utilizá-lo em App#show?

**Comment by filipewl** [comment]
@embs, utilizei ele lá também: https://github.com/redu/apps/commit/cd6fbf117b0b533019d4db9509ee8aa27f841ff9!

**Comment by embs** [comment]
Valeu, @filipewl. Evitastes uma crise existencial desse helper!
