### ISSUE TITLE
Renomear colunas das tabelas de componentes da hierarquia do Redu

### ISSUE THREAD

**Issue by embs** [redu/apps#92]
As colunas remetem ao ID das entidades no Redu. São elas:
- eid – Environment;
- cid – Course;
- sid – Space;
- suid – Subject;
- lid – Lecture; e
- aid – Application;

O objetivo da renomeação é dar nomes mais intuitivos a essas colunas.

**Comment by embs** [comment]
Sugestões?

Pensei em `environment_id`, `course_id`, `application_id`, etc. A chamada ao atributo ficaria `environment.environment_id` (por exemplo). O que acham? Outras alternativas que me vieram à mente foram `redu_id` ou `external_id`.

**Comment by guiocavalcanti** [comment]
@embs você pode usar core_id. Se for Environment#core_id, se trata do ID do environment do core. Que tal?

**Comment by fltiago** [comment]
Eu gostei da ideia de @guiocavalcanti, porque no caso de vocês colocarem `environment_id` poderia confundir mais a frente alguém. `environment.core_id` é uma boa solução.

**Comment by embs** [comment]
Também gostei da ideia!

**Comment by julianalucena** [comment]
Também gosto de `external_id`.

**Comment by guiocavalcanti** [comment]
só vejo um drawback de se usar external_id: nos casos em que for necessário guardar o ID de mais de um serviço esse atributo ficaria ambíguo.

**Comment by julianalucena** [comment]
Yeah, yeah.
