### ISSUE TITLE
Verificar uso das rotas abaixo

### ISSUE THREAD

**Issue by julianalucena** [redu/apps#94]
- Apps#preview
- Comments#show

**Comment by embs** [comment]
Comments#show é chamada [nesta view](https://github.com/redu/apps/blob/front-end-app-show/app/views/comments/_common_comment.html.erb#L41) e é usada para [carregar as respostas de um comentário](https://github.com/redu/apps/blob/front-end-app-show/app/controllers/comments_controller.rb#L8) – [renderizadas via js](https://github.com/redu/apps/blob/front-end-app-show/app/views/comments/show.js.erb).
